apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: hieunc
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: hieunc/hellov:1.0
